using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace testNetSuite
{
    public class Link
    {
        public string rel { get; set; }
        public string href { get; set; }
    }

    public class Item
    {
        public List<object> links { get; set; }
        public string alcoholrecipienttype { get; set; }
        public string altname { get; set; }
        public string balancesearch { get; set; }
        public string companyname { get; set; }
        public string creditholdoverride { get; set; }
        public string currency { get; set; }
        public string custentity_2663_customer_refund { get; set; }
        public string custentity_2663_direct_debit { get; set; }
        public string custentity_2663_email_address_notif { get; set; }
        public string custentity_atlas_high_impact { get; set; }
        public string custentity_naw_trans_need_approval { get; set; }
        public string custentity_wmsse_asn_required { get; set; }
        public string datecreated { get; set; }
        public string defaultbillingaddress { get; set; }
        public string defaultshippingaddress { get; set; }
        public string duplicate { get; set; }
        public string email { get; set; }
        public string emailpreference { get; set; }
        public string emailtransactions { get; set; }
        public string entityid { get; set; }
        public string entitystatus { get; set; }
        public string entitytitle { get; set; }
        public string faxtransactions { get; set; }
        public string firstsaledate { get; set; }
        public string giveaccess { get; set; }
        public string globalsubscriptionstatus { get; set; }
        public string id { get; set; }
        public string isautogeneratedrepresentingentity { get; set; }
        public string isbudgetapproved { get; set; }
        public string isinactive { get; set; }
        public string isperson { get; set; }
        public string lastmodifieddate { get; set; }
        public string lastsaledate { get; set; }
        public string oncredithold { get; set; }
        public string overduebalancesearch { get; set; }
        public string printtransactions { get; set; }
        public string probability { get; set; }
        public string receivablesaccount { get; set; }
        public string searchstage { get; set; }
        public string shipcomplete { get; set; }
        public string shippingcarrier { get; set; }
        public string unbilledorderssearch { get; set; }
        public string weblead { get; set; }
        public string fax { get; set; }
        public string phone { get; set; }
        public string accountnumber { get; set; }
        public string category { get; set; }
        public string custentity1 { get; set; }
        public string custentity_custclass { get; set; }
        public string custentity_esc_industry { get; set; }
        public string custentitycs_keyccount { get; set; }
        public string defaultallocationstrategy { get; set; }
        public string pricelevel { get; set; }
        public string terms { get; set; }
        public string territory { get; set; }
    }

    public class Root2
    {
        public List<Link> links { get; set; }
        public int count { get; set; }
        public bool hasMore { get; set; }
        public List<Item> items { get; set; }
        public int offset { get; set; }
        public int totalResults { get; set; }
    }
}
